"""
Verilog RTL generator for difflogic HardwareModel.

Generates:
  - A pure-combinational core module (model_core.v)
  - Optional pipelined variant (registered outputs per layer)

The generated Verilog is synthesisable and contains no behavioural
non-synthesisable constructs or delay statements.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from .hardware_ir import HardwareModel, LogicGate


# ---------------------------------------------------------------------------
# Gate-type → Verilog expression
# ---------------------------------------------------------------------------

def _gate_expr(gate_type: str, a: str, b: str) -> str:
    """Return the Verilog RHS expression for a gate."""
    t = gate_type.upper()
    if t == "ZERO":
        return "1'b0"
    elif t == "AND":
        return f"{a} & {b}"
    elif t == "NOT_IMPLIES":
        return f"{a} & ~{b}"
    elif t == "A":
        return a
    elif t == "NOT_IMPLIED_BY":
        return f"{b} & ~{a}"
    elif t == "B":
        return b
    elif t == "XOR":
        return f"{a} ^ {b}"
    elif t == "OR":
        return f"{a} | {b}"
    elif t == "NOT_OR":
        return f"~({a} | {b})"
    elif t == "NOT_XOR":
        return f"~({a} ^ {b})"
    elif t == "NOT_B":
        return f"~{b}"
    elif t == "IMPLIED_BY":
        return f"(~{b}) | {a}"
    elif t == "NOT_A":
        return f"~{a}"
    elif t == "IMPLIES":
        return f"(~{a}) | {b}"
    elif t == "NOT_AND":
        return f"~({a} & {b})"
    elif t == "ONE":
        return "1'b1"
    else:
        raise ValueError(f"Unknown gate type: {gate_type}")


def _wire_name(gate_id: int) -> str:
    return f"w{gate_id}"


def _input_ref(ref: int) -> str:
    """Convert an input reference to a Verilog signal name."""
    if ref < 0:
        return f"in[{-(ref + 1)}]"
    return _wire_name(ref)


class VerilogGenerator:
    """Generate synthesisable Verilog from a :class:`HardwareModel`."""

    def __init__(
        self,
        hw: HardwareModel,
        *,
        module_name: str = "model_core",
        pipelined: bool = False,
    ) -> None:
        self.hw = hw
        self.module_name = module_name
        self.pipelined = pipelined

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_core(self) -> str:
        """Return the complete Verilog source for the core module."""
        if self.pipelined:
            return self._generate_pipelined()
        return self._generate_combinational()

    def generate_and_save(self, path: str) -> None:
        """Write the core Verilog to *path*."""
        code = self.generate_core()
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(code)

    # ------------------------------------------------------------------
    # Combinational generation
    # ------------------------------------------------------------------

    def _generate_combinational(self) -> str:
        hw = self.hw
        n_in = hw.num_inputs
        n_out = len(hw.output_gate_ids)

        lines: List[str] = []
        lines.append(f"// Auto-generated by difflogic VerilogGenerator")
        lines.append(f"// Pure combinational – {hw.gate_count()} gates, "
                     f"depth {hw.max_depth()}")
        lines.append(f"")
        lines.append(f"module {self.module_name} (")
        lines.append(f"    input  wire        clk,")
        lines.append(f"    input  wire        rst,")
        lines.append(f"    input  wire [{n_in-1}:0] in,")
        lines.append(f"    output wire [{n_out-1}:0] out")
        lines.append(f");")
        lines.append(f"")

        # Declare all internal wires
        lines.append(f"    // Internal signal wires")
        for gate in hw.gates:
            lines.append(f"    wire {_wire_name(gate.gate_id)};")
        lines.append(f"")

        # Assign statements
        lines.append(f"    // Gate assignments")
        for gate in hw.gates:
            a_ref, b_ref = gate.input_ids
            a_sig = _input_ref(a_ref)
            b_sig = _input_ref(b_ref)
            expr = _gate_expr(gate.gate_type, a_sig, b_sig)
            lines.append(
                f"    assign {_wire_name(gate.gate_id)} = {expr};"
            )
        lines.append(f"")

        # Output assignments
        lines.append(f"    // Output assignments")
        for bit_idx, gid in enumerate(hw.output_gate_ids):
            lines.append(f"    assign out[{bit_idx}] = {_wire_name(gid)};")
        lines.append(f"")

        lines.append(f"endmodule")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Pipelined generation (register outputs between layers)
    # ------------------------------------------------------------------

    def _generate_pipelined(self) -> str:
        hw = self.hw
        n_in = hw.num_inputs
        n_out = len(hw.output_gate_ids)
        layers_map = hw.gates_by_layer()
        num_layers = max(layers_map.keys()) + 1 if layers_map else 1

        lines: List[str] = []
        lines.append(f"// Auto-generated by difflogic VerilogGenerator")
        lines.append(f"// Pipelined – {hw.gate_count()} gates, "
                     f"{num_layers} pipeline stages")
        lines.append(f"")
        lines.append(f"module {self.module_name} (")
        lines.append(f"    input  wire        clk,")
        lines.append(f"    input  wire        rst,")
        lines.append(f"    input  wire [{n_in-1}:0] in,")
        lines.append(f"    output reg  [{n_out-1}:0] out")
        lines.append(f");")
        lines.append(f"")

        # Declare wires for combinational part of each gate
        lines.append(f"    // Combinational wires")
        for gate in hw.gates:
            lines.append(f"    wire {_wire_name(gate.gate_id)}_c;")
        lines.append(f"")

        # Declare pipeline registers for each layer boundary
        lines.append(f"    // Pipeline registers per gate")
        for gate in hw.gates:
            lines.append(f"    reg  {_wire_name(gate.gate_id)};")
        lines.append(f"")

        # Combinational assignments
        lines.append(f"    // Combinational gate assignments")
        for gate in hw.gates:
            a_ref, b_ref = gate.input_ids
            # In the pipelined version, predecessor gates use their register
            a_sig = f"in[{-(a_ref+1)}]" if a_ref < 0 else f"{_wire_name(a_ref)}"
            b_sig = f"in[{-(b_ref+1)}]" if b_ref < 0 else f"{_wire_name(b_ref)}"
            expr = _gate_expr(gate.gate_type, a_sig, b_sig)
            lines.append(
                f"    assign {_wire_name(gate.gate_id)}_c = {expr};"
            )
        lines.append(f"")

        # Always block to register
        lines.append(f"    // Pipeline registers")
        lines.append(f"    always @(posedge clk or posedge rst) begin")
        lines.append(f"        if (rst) begin")
        for gate in hw.gates:
            lines.append(f"            {_wire_name(gate.gate_id)} <= 1'b0;")
        lines.append(f"        end else begin")
        for gate in hw.gates:
            lines.append(
                f"            {_wire_name(gate.gate_id)} <= "
                f"{_wire_name(gate.gate_id)}_c;"
            )
        lines.append(f"        end")
        lines.append(f"    end")
        lines.append(f"")

        # Output always block
        lines.append(f"    // Output register")
        lines.append(f"    always @(posedge clk or posedge rst) begin")
        lines.append(f"        if (rst) begin")
        lines.append(f"            out <= {n_out}'b0;")
        lines.append(f"        end else begin")
        for bit_idx, gid in enumerate(hw.output_gate_ids):
            lines.append(
                f"            out[{bit_idx}] <= {_wire_name(gid)};"
            )
        lines.append(f"        end")
        lines.append(f"    end")
        lines.append(f"")

        lines.append(f"endmodule")
        return "\n".join(lines)
