// model_core.v.tpl – Jinja2 / simple string-format template
// Auto-filled by VerilogGenerator; kept here as documentation reference.
//
// Variables:
//   {{ module_name }}  – top-level module name
//   {{ n_in }}         – number of primary inputs
//   {{ n_out }}        – number of primary outputs
//   {{ gate_count }}   – total number of logic gates
//   {{ max_depth }}    – critical path depth
//   {{ wires }}        – wire declarations block
//   {{ assigns }}      – assign statements block
//   {{ out_assigns }}  – output port assignments block

// Auto-generated by difflogic VerilogGenerator
// Gates: {{ gate_count }}  Depth: {{ max_depth }}

module {{ module_name }} (
    input  wire        clk,
    input  wire        rst,
    input  wire [{{ n_in - 1 }}:0] in,
    output wire [{{ n_out - 1 }}:0] out
);

    // Internal signal wires
{{ wires }}

    // Gate assignments
{{ assigns }}

    // Output assignments
{{ out_assigns }}

endmodule
